# Generated by Django 3.1.1 on 2020-11-14 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('cupo_credito', models.FloatField(default=2000000, max_length=10)),
                ('puntos', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Activo', max_length=12)),
                ('acepta_email', models.BooleanField(verbose_name='Acepta envio de mail')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CuentaCliente',
            },
        ),
    ]
