# Generated by Django 3.1.1 on 2020-11-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Canal',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('especificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio_venta', models.FloatField(default=0, max_length=10)),
                ('img', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=100)),
                ('fec_ini', models.DateTimeField(auto_now_add=True)),
                ('fec_fin', models.DateField(max_length=20)),
                ('precio_nuevo', models.FloatField(default=0, max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Vigente', max_length=12)),
                ('img', models.CharField(max_length=50)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.canal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'Promociones',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo'),
        ),
    ]
